apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: architect-dev

resources:
  - ../../base
  - ../../infrastructure
  - ../../services

images:
  - name: architect-backend
    newTag: "0.1.0"
  - name: architect-frontend
    newTag: "0.1.0"
  - name: architect-db-migrations
    newTag: "0.1.0"
